# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# 按字段分组导出要素.py
# Created on: 2018-01-04 10:30:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: 按字段分组导出要素 <输入要素> <按字段分组> <工作空间> <跳过空值> <输出要素类> <prefix> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("模型函数")

# Script arguments
输入要素 = arcpy.GetParameterAsText(0)

按字段分组 = arcpy.GetParameterAsText(1)

工作空间 = arcpy.GetParameterAsText(2)

跳过空值 = arcpy.GetParameterAsText(3)
if 跳过空值 == '#' or not 跳过空值:
    跳过空值 = "false" # provide a default value if unspecified

输出要素类 = arcpy.GetParameterAsText(4)

prefix = arcpy.GetParameterAsText(5)

# Local variables:
所选要素 = 输入要素
value = 输入要素
suffix = ""

# Process: 迭代要素选择
# 此工具专用于模型构建器，而并不在编写 Python 脚本时使用。
# XXX_mb工具专用于模型构建器
arcpy.IterateFeatureSelection_mb(输入要素, 按字段分组, 跳过空值)

# Process: 要素类至要素类
arcpy.FeatureClassToFeatureClass_conversion(所选要素, 工作空间, "%prefix%%value%", "", "", "")

